---
title: "台灣各地區登革熱分析"
output: github_document
---

##讀入資料
```{r}
#這是R Code Chunk
library(readr)
#99~106年高雄登革熱資料
MosIndex_Kaohsiung <- read_csv("C:/Users/user/Downloads/MosIndex_Kaohsiung.csv")
#104年高雄各地區各月份病例資料
X104dengueinfection <- read_csv("C:/Users/user/Downloads/104dengueinfection.csv")
#台南市、高雄市、屏東縣快篩診所資料
ns1hosp_20160603 <- read_csv("C:/Users/user/Downloads/ns1hosp_20160603.csv")
#99~106年全台登革熱資料
MosIndex_All <- read_csv("C:/Users/user/Downloads/MosIndex_All.csv")
#104年全台各鄉鎮市區人口密度
opendata104N010 <- read_csv("C:/Users/user/Downloads/opendata104N010.csv")
```

##資料處理與清洗、資料視覺化(99~106年全台登革熱資料)
```{r}
#這是R Code Chunk
library(dplyr)
MosIndex_Allc<-select(MosIndex_All,Date:AreaType)
MosIndex_Allc<-MosIndex_Allc[complete.cases(MosIndex_Allc),]
MosIndex_Allc$VillageLon<-as.numeric(MosIndex_Allc$VillageLon)
MosIndex_Allc$VillageLat<-as.numeric(MosIndex_Allc$VillageLat)
MosIndex_Allc2010<-MosIndex_Allc[grepl("2010",MosIndex_Allc$Date),]
MosIndex_Allc2011<-MosIndex_Allc[grepl("2011",MosIndex_Allc$Date),]
MosIndex_Allc2012<-MosIndex_Allc[grepl("2012",MosIndex_Allc$Date),]
MosIndex_Allc2013<-MosIndex_Allc[grepl("2013",MosIndex_Allc$Date),]
MosIndex_Allc2014<-MosIndex_Allc[grepl("2014",MosIndex_Allc$Date),]
MosIndex_Allc2015<-MosIndex_Allc[grepl("2015",MosIndex_Allc$Date),]
MosIndex_Allc2016<-MosIndex_Allc[grepl("2016",MosIndex_Allc$Date),]
MosIndex_Allc2017<-MosIndex_Allc[grepl("2017",MosIndex_Allc$Date),]
library(ggmap)
Taiwanmap <- get_map(location = "Taiwan", zoom = 8)
densityMap0<-ggmap(Taiwanmap,extent = "device")+ 
  geom_density2d(data = MosIndex_Allc2010, aes(x = VillageLon, y = VillageLat), size = 0.3)+
  stat_density2d(data = MosIndex_Allc2010, 
                 aes(x = VillageLon, y = VillageLat, 
                     fill = ..level.., alpha = ..level..), 
                 size = 0.01, bins = 16, geom = "polygon") + 
  scale_fill_gradient(low = "green", 
                      high = "red", guide = FALSE) + 
  scale_alpha(range = c(0, 0.3), guide = FALSE)
densityMap0
Taiwanmap <- get_map(location = "Taiwan", zoom = 8)
densityMap1<-ggmap(Taiwanmap,extent = "device")+ 
  geom_density2d(data = MosIndex_Allc2011, aes(x = VillageLon, y = VillageLat), size = 0.3)+
  stat_density2d(data = MosIndex_Allc2011, 
                 aes(x = VillageLon, y = VillageLat, 
                     fill = ..level.., alpha = ..level..), 
                 size = 0.01, bins = 16, geom = "polygon") + 
  scale_fill_gradient(low = "green", 
                      high = "red", guide = FALSE) + 
  scale_alpha(range = c(0, 0.3), guide = FALSE)
densityMap1
Taiwanmap <- get_map(location = "Taiwan", zoom = 8)
densityMap2<-ggmap(Taiwanmap,extent = "device")+ 
  geom_density2d(data = MosIndex_Allc2012, aes(x = VillageLon, y = VillageLat), size = 0.3)+
  stat_density2d(data = MosIndex_Allc2012, 
                 aes(x = VillageLon, y = VillageLat, 
                     fill = ..level.., alpha = ..level..), 
                 size = 0.01, bins = 16, geom = "polygon") + 
  scale_fill_gradient(low = "green", 
                      high = "red", guide = FALSE) + 
  scale_alpha(range = c(0, 0.3), guide = FALSE)
densityMap2
Taiwanmap <- get_map(location = "Taiwan", zoom = 8)
densityMap3<-ggmap(Taiwanmap,extent = "device")+ 
  geom_density2d(data = MosIndex_Allc2013, aes(x = VillageLon, y = VillageLat), size = 0.3)+
  stat_density2d(data = MosIndex_Allc2013, 
                 aes(x = VillageLon, y = VillageLat, 
                     fill = ..level.., alpha = ..level..), 
                 size = 0.01, bins = 16, geom = "polygon") + 
  scale_fill_gradient(low = "green", 
                      high = "red", guide = FALSE) + 
  scale_alpha(range = c(0, 0.3), guide = FALSE)
densityMap3
densityMap4<-ggmap(Taiwanmap,extent = "device")+ 
  geom_density2d(data = MosIndex_Allc2014, aes(x = VillageLon, y = VillageLat), size = 0.3)+
  stat_density2d(data = MosIndex_Allc2014, 
                 aes(x = VillageLon, y = VillageLat, 
                     fill = ..level.., alpha = ..level..), 
                 size = 0.01, bins = 16, geom = "polygon") + 
  scale_fill_gradient(low = "green", 
                      high = "red", guide = FALSE) + 
  scale_alpha(range = c(0, 0.3), guide = FALSE)
densityMap4
Taiwanmap <- get_map(location = "Taiwan", zoom = 8)
densityMap5<-ggmap(Taiwanmap,extent = "device")+ 
  geom_density2d(data = MosIndex_Allc2015, aes(x = VillageLon, y = VillageLat), size = 0.3)+
  stat_density2d(data = MosIndex_Allc2015, 
                 aes(x = VillageLon, y = VillageLat, 
                     fill = ..level.., alpha = ..level..), 
                 size = 0.01, bins = 16, geom = "polygon") + 
  scale_fill_gradient(low = "green", 
                      high = "red", guide = FALSE) + 
  scale_alpha(range = c(0, 0.3), guide = FALSE)
densityMap5
Taiwanmap <- get_map(location = "Taiwan", zoom = 8)
densityMap6<-ggmap(Taiwanmap,extent = "device")+ 
  geom_density2d(data = MosIndex_Allc2016, aes(x = VillageLon, y = VillageLat), size = 0.3)+
  stat_density2d(data = MosIndex_Allc2016, 
                 aes(x = VillageLon, y = VillageLat, 
                     fill = ..level.., alpha = ..level..), 
                 size = 0.01, bins = 16, geom = "polygon") + 
  scale_fill_gradient(low = "green", 
                      high = "red", guide = FALSE) + 
  scale_alpha(range = c(0, 0.3), guide = FALSE)
densityMap6
Taiwanmap <- get_map(location = "Taiwan", zoom = 8)
densityMap7<-ggmap(Taiwanmap,extent = "device")+ 
  geom_density2d(data = MosIndex_Allc2017, aes(x = VillageLon, y = VillageLat), size = 0.3)+
  stat_density2d(data = MosIndex_Allc2017, 
                 aes(x = VillageLon, y = VillageLat, 
                     fill = ..level.., alpha = ..level..), 
                 size = 0.01, bins = 16, geom = "polygon") + 
  scale_fill_gradient(low = "green", 
                      high = "red", guide = FALSE) + 
  scale_alpha(range = c(0, 0.3), guide = FALSE)
densityMap7
```

##資料處理與清洗、資料視覺化(99~106年高雄登革熱資料)
```{r}
library(dplyr)
MosIndex_Kaohsiungc<-select(MosIndex_Kaohsiung,Date:AreaType)
MosIndex_Kaohsiungc2015<-MosIndex_Kaohsiungc[grepl("2015",MosIndex_Kaohsiungc$Date),]
MosIndex_Kaohsiungc2016<-MosIndex_Kaohsiungc[grepl("2016",MosIndex_Kaohsiungc$Date),]
library(ggmap)
khcmap <- get_map(location ='Kaohsiung', 
                 zoom = 10,
                 language = "zh-TW", maptype = 'roadmap')
khcmap1 <- ggmap(khcmap)+ 
  geom_point(data=MosIndex_Kaohsiungc, 
             aes(x=VillageLon, y=VillageLat),colour="red")
khcmap1
```
##資料處理與清洗、資料視覺化(104年高雄各地區各月份病例資料)
```{r}
X104dengueinfectionC<-select(X104dengueinfection,行政區:`12月`)
library(reshape2)
X104dengueinfectionM<-melt(X104dengueinfectionC,id.vars = "行政區")
X104dengueinfectionM1<-X104dengueinfectionM[grepl("區",X104dengueinfectionM$行政區),]
#104年各月份高雄地區的病例數
test<-group_by(X104dengueinfectionM1,variable) %>%
  summarise(次數=sum(value,na.rm=T))%>%
  arrange(desc(次數))
test
ggplot()+geom_bar(data=test,aes(x= variable,y= 次數),
                  stat = "identity")+xlab("月份")
#104年高雄各地區的總病例
test1<-group_by(X104dengueinfectionM1,.dots=行政區) %>%
 summarise(病例=sum(value,na.rm=T)) %>%
    arrange(desc(病例))
test1<-rename(test1,site_id=.dots)
test1
```
##資料處理與清洗、資料視覺化(台南市、高雄市、屏東縣快篩診所資料)
```{r}
ns1hosp_20160603K<- ns1hosp_20160603[grep("高雄市",ns1hosp_20160603$city),]
#登革熱快篩所與病例分布
library(ggmap)
Kaohsiungmap <- get_map(location = "Kaohsiung", zoom = 10,
                        language = "zh-TW", maptype = "roadmap")
#紅色是病例，綠色是快篩所
Kaohsiungmap0 <- ggmap(Kaohsiungmap)+ 
  geom_point(data=MosIndex_Kaohsiungc2015, 
             aes(x = VillageLon, y = VillageLat),
             colour="red",size=1.2)+
  geom_point(data=ns1hosp_20160603K, 
             aes(x = lng, y = lat),
             colour="green",size=1.2)
Kaohsiungmap0
```
##資料處理與清洗、資料視覺化(104年全台各鄉鎮市區人口密度)
```{r}
opendata104N010C<-opendata104N010[grepl("高雄市",opendata104N010$site_id),]
opendata104N010C<-opendata104N010C[complete.cases(opendata104N010C$statistic_yyy),]
opendata104N010C$site_id<-substr(opendata104N010C$site_id,start = 4,stop = 7)
a<-full_join(opendata104N010C,test1,by="site_id")
a<-mutate(a,盛行率=病例/as.numeric(people_total))
```